# Generated by Django 5.1.1 on 2026-01-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuantumBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_hash', models.CharField(max_length=256)),
                ('previous_hash', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField()),
                ('data_summary', models.TextField()),
            ],
        ),
    ]
