# Generated by Django 5.1.1 on 2026-03-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_alter_quantumblock_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=100)),
                ('predicted_class', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shap_summary', models.TextField()),
                ('stored_hash', models.CharField(max_length=256)),
                ('transaction_receipt', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='QuantumBlock',
        ),
    ]
